# *
# * This Source Code Form is subject to the terms of the Mozilla Public
# * License, v. 2.0. If a copy of the MPL was not distributed with this
# * file, You can obtain one at http://mozilla.org/MPL/2.0/.
# *

version: "2"
services:
    # Database service. It's PostgreSQL, see the
    # Dockerfile in ./database
    database:
        build: ./database/
        environment:
            # Custom PGDATA per recommendations from official Docker page
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgres-data:/var/lib/postgresql/data/pgdata
    # Web service runs Node
    web:
        # Configuration variables for the app.
        environment:
            - OED_SERVER_PORT=3000
            - OED_DB_USER=oed
            - OED_DB_DATABASE=oed
            - OED_DB_TEST_DATABASE=oed_testing
            - OED_DB_PASSWORD=opened
            - OED_DB_HOST=database # Docker will set this hostname
            - OED_DB_PORT=5432
            - OED_TOKEN_SECRET=?
            - OED_LOG_FILE=log.txt
            - OED_MAIL_METHOD=gmail # Method of sending mail. Supports "gmail", "mailgun", "none". Case insensitive.
            - OED_MAIL_IDENT=prestonbui97@gmail.com
            - OED_MAIL_CREDENTIAL=Prowebdesigner97! # Set the email password here
            - OED_MAIL_FROM=prestonbui97@gmail.com
            - OED_MAIL_TO=buip@beloit.edu # Set the destination address here
            - OED_MAIL_ORG=My Organization Name
        # Set the correct build environment.
        build: ./
        # Link to the database so the app can persist data
        links:
            - database
        # Load the source code into the container.
        # Using a volume allows autorebuild to work.
        volumes:
            - ./:/usr/src/app
        # Map the default port.
        ports:
            - "3000:3000"
              # For production you might want something like:
              # - "80:3000"
        # Don't bring this up without the DB
        depends_on:
            - database
        # Lets docker-compose up work right
        command: ["npm", "start"]
